Milestone 2 - Connor OBrien
hack4impact-calpoly/milestone2_2022 pull request #14
Opened 2022-10-30 18:04 UTC by connorpobrien

# Milestone: #2
# Developer: Connor O'Brien

### Pull Request Summary

Submission for milestone 2

### Pull Request Checklist
- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit message follows our guidelines
- [x] The milestone number is specified
- [x] The developer name is specified
- [x] The summary is completed

### Reviewer Checklist  - PULL REQUEST REVIEWER ONLY

IMPORTANT: The rest of the sections in this checklist should only be filled out by authorized pull request reviewers. If you are the individual template contributor, do not fill out the rest of the fields or check the boxes.

NOTE: Milestones can only be completed when all boxes are checked.

- [ ] The code is fully reviewed
- [ ] Meaningful feedback is given
- [ ] Comment that you have reviewed the code
- [ ] This box is checked

2022-11-08 23:25 UTC, vwinstea requested changes
Great work! All of the tests pass, but before wrapping up this milestone, please update your code for questions 2-4 and 7 by following the comments below.

2022-11-08 23:25 UTC, vwinstea commented on milestone2.ts
> +  return -1;
For questions 2-4 please use the data handling functions shown [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array). For loops are good, but its important to be familiar with lambda function syntax too. Sorry if the instructions were unclear!

2022-11-08 23:25 UTC, vwinstea commented on milestone2.ts
> +  let city = vol.city;
Please use [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#object_destructuring) for this question

2022-11-10 21:31 UTC, connorpobrien commented
changes made ✅

2022-11-13 16:09 UTC, vwinstea reviewed
Much better, thanks for making the fixes! Question 7 is still a bit off, you used array destructuring instead of [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#object_destructuring), but that was a pretty common mistake for this milestone. Nice work!

2022-11-13 16:09 UTC, vwinstea commented
Milestone 2 complete!

2022-11-13 16:09 UTC, closed without merging